Repository TTG-Club/ttg-club-backend, pull requests merged in 2022-11, with the labels that each got.

#6 fix lair description
  src/main/java/club/dnd5/portal/controller/api/GlobalSearchController.java
  src/main/java/club/dnd5/portal/dto/api/SearchApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/LairApi.java
  src/main/java/club/dnd5/portal/repository/datatable/TraitDatatableRepository.java
Labels: bug

#7 fix lair descriptions in bestiary
  src/main/java/club/dnd5/portal/controller/api/GlobalSearchController.java
  src/main/java/club/dnd5/portal/dto/api/SearchApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/LairApi.java
  src/main/java/club/dnd5/portal/repository/datatable/TraitDatatableRepository.java
Labels: bug

#9 D5-60: Problema-c-kanonichnymi-ssylkami
  src/main/java/club/dnd5/portal/controller/ArmorController.java
  src/main/java/club/dnd5/portal/controller/BackgroundController.java
  src/main/java/club/dnd5/portal/controller/BestiaryController.java
  src/main/java/club/dnd5/portal/controller/ClassController.java
  src/main/java/club/dnd5/portal/controller/GodController.java
  src/main/java/club/dnd5/portal/controller/ItemController.java
  src/main/java/club/dnd5/portal/controller/MagicItemController.java
  src/main/java/club/dnd5/portal/controller/OptionController.java
  src/main/java/club/dnd5/portal/controller/RaceController.java
  src/main/java/club/dnd5/portal/controller/RuleController.java
  src/main/java/club/dnd5/portal/controller/ScreenController.java
  src/main/java/club/dnd5/portal/controller/SpellController.java
  src/main/java/club/dnd5/portal/controller/TraitController.java
  src/main/java/club/dnd5/portal/controller/TreasureController.java
  src/main/java/club/dnd5/portal/controller/WeaponController.java
  src/main/java/club/dnd5/portal/controller/api/MetaApiController.java
  src/main/java/club/dnd5/portal/model/god/God.java
  src/main/java/club/dnd5/portal/model/items/Armor.java
  src/main/java/club/dnd5/portal/model/screen/Screen.java
Labels: bug

#10 D5-63: Разные канонические ссылки на одно и то-же странице
  src/main/java/club/dnd5/portal/controller/ArmorController.java
  src/main/java/club/dnd5/portal/controller/BackgroundController.java
  src/main/java/club/dnd5/portal/controller/BestiaryController.java
  src/main/java/club/dnd5/portal/controller/BookController.java
  src/main/java/club/dnd5/portal/controller/ClassController.java
  src/main/java/club/dnd5/portal/controller/GodController.java
  src/main/java/club/dnd5/portal/controller/ItemController.java
  src/main/java/club/dnd5/portal/controller/MagicItemController.java
  src/main/java/club/dnd5/portal/controller/OptionController.java
  src/main/java/club/dnd5/portal/controller/RaceController.java
  src/main/java/club/dnd5/portal/controller/RuleController.java
  src/main/java/club/dnd5/portal/controller/ScreenController.java
  src/main/java/club/dnd5/portal/controller/SpellController.java
  src/main/java/club/dnd5/portal/controller/TraitController.java
  src/main/java/club/dnd5/portal/controller/WeaponController.java
  src/main/java/club/dnd5/portal/controller/tools/AbilityCalculatorController.java
  src/main/java/club/dnd5/portal/model/items/Armor.java
  src/main/java/club/dnd5/portal/model/items/Equipment.java
  src/main/java/club/dnd5/portal/model/items/MagicItem.java
  src/main/java/club/dnd5/portal/model/items/Weapon.java
Labels: bug

#11 fix barbarian
  src/main/java/club/dnd5/portal/model/names/NameOwner.java
  src/main/resources/templates/fragments/class.html
Labels: good first issue

#12 Fixlogo and ttg bot link
  src/main/resources/templates/fragments/menu.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/layout.html
  src/main/resources/templates/telegram_bot.html
Labels: enhancement

#14 Fix meta img
  src/main/resources/templates/layouts/layout.html
Labels: good first issue

#17 Christmas
  src/main/java/club/dnd5/portal/controller/RaceController.java
  src/main/java/club/dnd5/portal/controller/api/MetaApiController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/layout.html
Labels: good first issue
