Repository TTG-Club/ttg-club-backend, pull requests merged in 2023-10, with the labels that each got.

#86 Fix Timecast Filtering Logic
  src/main/java/club/dnd5/portal/controller/api/SpellApiController.java
  src/main/java/club/dnd5/portal/util/SpecificationUtil.java
Labels: bug

#87 Markdown
  src/main/java/club/dnd5/portal/controller/api/tools/MadnessApiController.java
  src/main/java/club/dnd5/portal/controller/api/tools/TraderApiController.java
  src/main/java/club/dnd5/portal/dto/api/NameValueApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/BeastDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/SenseApi.java
  src/main/java/club/dnd5/portal/dto/api/races/RaceApi.java
  src/main/java/club/dnd5/portal/dto/api/races/RaceDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/tools/MadnessApi.java
  src/main/java/club/dnd5/portal/dto/api/tools/RandomEncounterInputApi.java
  src/main/java/club/dnd5/portal/model/creature/Action.java
  src/main/java/club/dnd5/portal/model/creature/ActionData.java
  src/main/java/club/dnd5/portal/model/creature/Creature.java
  src/main/java/club/dnd5/portal/model/creature/CreatureFeat.java
  src/main/java/club/dnd5/portal/util/MarkdownUtil.java
  src/test/java/club/dnd5/portal/MarkdownTest.java
Labels: enhancement

#90 Dev bugfix/bestiary spells
  src/main/java/club/dnd5/portal/controller/api/JsonParseController.java
  src/main/java/club/dnd5/portal/controller/api/SpellApiController.java
  src/main/java/club/dnd5/portal/controller/api/bestiary/BestiaryApiController.java
  src/main/java/club/dnd5/portal/dto/fvtt/export/SRD5e.java
  src/main/java/club/dnd5/portal/dto/fvtt/export/spell/FSpell.java
  src/main/java/club/dnd5/portal/dto/fvtt/export/system/FSystemSpell.java
  src/main/java/club/dnd5/portal/dto/fvtt/export/token/FFlags.java
  src/main/java/club/dnd5/portal/model/FoundryCommon.java
  src/main/java/club/dnd5/portal/model/JsonStorageCompositeKey.java
  src/main/java/club/dnd5/portal/model/JsonType.java
  src/main/java/club/dnd5/portal/model/creature/Creature.java
  src/main/java/club/dnd5/portal/model/exporter/JsonStorage.java
  src/main/java/club/dnd5/portal/model/splells/Spell.java
  src/main/java/club/dnd5/portal/repository/JsonStorageRepository.java
  src/main/java/club/dnd5/portal/service/JsonStorageService.java
  src/main/java/club/dnd5/portal/service/JsonStorageServiceImpl.java
Labels: feature
