Repository TTG-Club/ttg-club-backend, pull requests merged in 2023-04, with the labels that each got.

#46 Class race groups
  src/main/java/club/dnd5/portal/controller/api/ClassApiController.java
  src/main/java/club/dnd5/portal/dto/api/classes/ClassApi.java
  src/main/java/club/dnd5/portal/dto/api/races/RaceApi.java
Labels: enhancement

#47 fix
  src/main/java/club/dnd5/portal/dto/api/classes/ClassApi.java
Labels: enhancement

#48 update classes
  src/main/java/club/dnd5/portal/dto/api/classes/ClassApi.java
Labels: enhancement

#49 new release
  src/main/java/club/dnd5/portal/controller/ClassController.java
  src/main/java/club/dnd5/portal/controller/api/ClassApiController.java
  src/main/java/club/dnd5/portal/dto/api/classes/ClassApi.java
  src/main/java/club/dnd5/portal/dto/api/races/RaceApi.java
  src/main/java/club/dnd5/portal/model/races/Race.java
Labels: release

#50 hotfix: classes type switch
  src/main/java/club/dnd5/portal/dto/api/classes/ClassApi.java
  src/main/java/club/dnd5/portal/model/classes/Option.java
Labels: bug, release

#54 fix: bug
  src/main/java/club/dnd5/portal/dto/api/races/RaceDetailApi.java
  src/main/java/club/dnd5/portal/dto/fvtt/export/FDiscription.java
  src/main/java/club/dnd5/portal/repository/SearchRepository.java
Labels: bug
