Repository TTG-Club/ttg-club-backend, pull requests merged in 2023-11, with the labels that each got.

#98 Feature - News banner
  src/main/java/club/dnd5/portal/config/WebSecurityConfig.java
  src/main/java/club/dnd5/portal/controller/api/NewsBannerApiController.java
  src/main/java/club/dnd5/portal/controller/api/YoutubeVideoApiController.java
  src/main/java/club/dnd5/portal/dto/api/NewsBannerApi.java
  src/main/java/club/dnd5/portal/model/NewsBanner.java
  src/main/java/club/dnd5/portal/repository/NewsBannerRepository.java
  src/main/java/club/dnd5/portal/util/SpecificationUtil.java
Labels: feature

#100 hotfix: Add reaction text
  src/main/java/club/dnd5/portal/dto/api/bestiary/BeastDetailApi.java
Labels: enhancement

#101 hotfix: reaction
  src/main/java/club/dnd5/portal/controller/api/SpellApiController.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/BeastDetailApi.java
Labels: bug

#97 Added a new Entity / API (Configuration)
  src/main/java/club/dnd5/portal/controller/api/SiteConfigurationApiController.java
  src/main/java/club/dnd5/portal/model/SiteConfiguration.java
  src/main/java/club/dnd5/portal/repository/SiteConfigurationRepository.java
Labels: feature

#99 Ttg 32 feature/armor filter
  src/main/java/club/dnd5/portal/controller/api/item/ArmorApiController.java
  src/main/java/club/dnd5/portal/dto/api/FilterValueApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorFilter.java
  src/main/java/club/dnd5/portal/repository/datatable/ArmorRepository.java
Labels: feature

#102 Fixed bug with a distance filter
  src/main/java/club/dnd5/portal/controller/api/SpellApiController.java
Labels: bug

#104 Dev
  src/main/java/club/dnd5/portal/controller/BestiaryController.java
  src/main/java/club/dnd5/portal/controller/api/SiteConfigurationApiController.java
  src/main/java/club/dnd5/portal/controller/api/SpellApiController.java
  src/main/java/club/dnd5/portal/controller/api/item/ArmorApiController.java
  src/main/java/club/dnd5/portal/dto/api/FilterValueApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorFilter.java
  src/main/java/club/dnd5/portal/model/DamageType.java
  src/main/java/club/dnd5/portal/model/SiteConfiguration.java
  src/main/java/club/dnd5/portal/repository/SiteConfigurationRepository.java
  src/main/java/club/dnd5/portal/repository/datatable/ArmorRepository.java
Labels: release
