Repository TTG-Club/ttg-club-backend, pull requests merged in 2024-01, with the labels that each got.

#105 Добавление суффикса для отображения в таблице класса
  src/main/java/club/dnd5/portal/model/classes/HeroClassTrait.java
  src/main/java/club/dnd5/portal/model/classes/archetype/ArchetypeTrait.java
  src/main/resources/templates/fragments/archetype.html
  src/main/resources/templates/fragments/class.html
Labels: enhancement

#106 TTG 39 Tokenator 2.0 (Token Border)
  src/main/java/club/dnd5/portal/controller/api/TokenBorderApiController.java
  src/main/java/club/dnd5/portal/exception/StorageException.java
  src/main/java/club/dnd5/portal/model/token/TokenBorder.java
  src/main/java/club/dnd5/portal/repository/TokenBorderRepository.java
  src/main/java/club/dnd5/portal/service/TokenBorderService.java
  src/main/java/club/dnd5/portal/service/TokenBorderServiceImpl.java
  src/main/java/club/dnd5/portal/util/NotHandlerControllerAdvice.java
Labels: feature

#107 Feature/bestiary editor
  src/main/java/club/dnd5/portal/controller/FeatController.java
  src/main/java/club/dnd5/portal/controller/GodController.java
  src/main/java/club/dnd5/portal/controller/MagicItemController.java
  src/main/java/club/dnd5/portal/controller/api/DirectoryControllerApi.java
  src/main/java/club/dnd5/portal/controller/api/FeatApiController.java
  src/main/java/club/dnd5/portal/controller/api/FvttApiController.java
  src/main/java/club/dnd5/portal/controller/api/MetaApiController.java
  src/main/java/club/dnd5/portal/controller/api/SpellApiController.java
  src/main/java/club/dnd5/portal/controller/api/TokenApiController.java
  src/main/java/club/dnd5/portal/controller/api/bestiary/Bestiary2ApiController.java
  src/main/java/club/dnd5/portal/controller/api/bestiary/BestiaryApiController.java
  src/main/java/club/dnd5/portal/controller/api/item/WeaponApiController.java
  src/main/java/club/dnd5/portal/controller/api/tools/TraderApiController.java
  src/main/java/club/dnd5/portal/controller/api/tools/TreasuryApiController.java
  src/main/java/club/dnd5/portal/controller/api/wiki/GodApiController.java
  src/main/java/club/dnd5/portal/dto/ConditionDto.java
  src/main/java/club/dnd5/portal/dto/api/DirectoryApi.java
  src/main/java/club/dnd5/portal/dto/api/NameValueApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/AbilityApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/BeastApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/BeastDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/BeastFilter.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/BeastRequesApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/HitPointsApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/LairApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/LegendaryApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/SenseApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/SizeApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/request/BeastDetailRequest.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/request/HitRequest.java
  src/main/java/club/dnd5/portal/dto/api/classes/NameApi.java
  src/main/java/club/dnd5/portal/dto/api/item/WeaponApi.java
  src/main/java/club/dnd5/portal/dto/api/spell/SpellApi.java
  src/main/java/club/dnd5/portal/dto/api/spells/SearchRequest.java
  src/main/java/club/dnd5/portal/dto/api/spells/SpellFvtt.java
  src/main/java/club/dnd5/portal/dto/api/wiki/GodApi.java
  src/main/java/club/dnd5/portal/dto/fvtt/export/FItem.java
  src/main/java/club/dnd5/portal/dto/fvtt/export/system/details/FDetails.java
  src/main/java/club/dnd5/portal/model/Alignment.java
  src/main/java/club/dnd5/portal/model/DamageType.java
  src/main/java/club/dnd5/portal/model/Rest.java
  src/main/java/club/dnd5/portal/model/classes/HeroClass.java
  src/main/java/club/dnd5/portal/model/creature/Action.java
  src/main/java/club/dnd5/portal/model/creature/Condition.java
  src/main/java/club/dnd5/portal/model/creature/CreatureFeat.java
  src/main/java/club/dnd5/portal/model/splells/Spell.java
  src/main/java/club/dnd5/portal/repository/datatable/FeatRepository.java
Labels: enhancement, feature

#108 создание сервиса для бестиария, переделка справочников
  src/main/java/club/dnd5/portal/controller/api/DirectoryControllerApi.java
  src/main/java/club/dnd5/portal/controller/api/bestiary/Bestiary2ApiController.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/request/BeastDetailRequest.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/request/DescriptionRequest.java
  src/main/java/club/dnd5/portal/service/BestiaryService.java
  src/main/java/club/dnd5/portal/service/BestiaryServiceImpl.java
Labels: feature

#109 исправление справочника
  src/main/java/club/dnd5/portal/controller/api/DirectoryControllerApi.java
  src/main/java/club/dnd5/portal/dto/api/ValueApi.java
  src/main/java/club/dnd5/portal/dto/api/bestiary/request/BeastDetailRequest.java
  src/main/java/club/dnd5/portal/service/BestiaryServiceImpl.java
Labels: enhancement, feature

#103 feat: add tokenator meta
  src/main/java/club/dnd5/portal/controller/api/MetaApiController.java
Labels: feature

#111 Bugfix security saving files
  src/main/java/club/dnd5/portal/service/TokenBorderServiceImpl.java
Labels: bug
