Repository TTG-Club/ttg-club-backend, pull requests merged in 2024-03, with the labels that each got.

#117 release
  src/main/java/club/dnd5/portal/dto/api/bestiary/BeastDetailApi.java
  src/main/java/club/dnd5/portal/model/creature/Creature.java
Labels: release

#118 нагрудник на кирасу
  src/main/java/club/dnd5/portal/model/ArmorType.java
Labels: bug

#119 Хотфикс нагрудник на кирасу
  src/main/java/club/dnd5/portal/model/ArmorType.java
Labels: bug

#116 TTG-41 TTG Party
  src/main/java/club/dnd5/portal/PortalApplication.java
  src/main/java/club/dnd5/portal/config/ValueProvider.java
  src/main/java/club/dnd5/portal/controller/api/InvitationApiController.java
  src/main/java/club/dnd5/portal/controller/api/UserPartyApiController.java
  src/main/java/club/dnd5/portal/dto/api/InvitationApi.java
  src/main/java/club/dnd5/portal/dto/api/PartyMember.java
  src/main/java/club/dnd5/portal/dto/api/UserApi.java
  src/main/java/club/dnd5/portal/dto/api/UserPartyApi.java
  src/main/java/club/dnd5/portal/dto/api/UserPartyCreateApi.java
  src/main/java/club/dnd5/portal/dto/api/UserPartyFilter.java
  src/main/java/club/dnd5/portal/dto/api/UserPartyRequestApi.java
  src/main/java/club/dnd5/portal/model/Invitation.java
  src/main/java/club/dnd5/portal/model/user/User.java
  src/main/java/club/dnd5/portal/model/user/UserParty.java
  src/main/java/club/dnd5/portal/repository/InvitationRepository.java
  src/main/java/club/dnd5/portal/repository/UserPartyRepository.java
  src/main/java/club/dnd5/portal/service/EmailService.java
  src/main/java/club/dnd5/portal/service/InvitationService.java
  src/main/java/club/dnd5/portal/service/InvitationServiceImpl.java
  src/main/java/club/dnd5/portal/service/TokenBorderServiceImpl.java
  src/main/java/club/dnd5/portal/service/UserPartyService.java
  src/main/java/club/dnd5/portal/service/UserPartyServiceImpl.java
  src/main/resources/application.properties
Labels: feature

#120 Feature/LSS
  src/main/java/club/dnd5/portal/controller/api/FvttApiController.java
  src/main/java/club/dnd5/portal/controller/api/JsonParseController.java
  src/main/java/club/dnd5/portal/controller/api/LssApiController.java
  src/main/java/club/dnd5/portal/model/FoundryVersion.java
  src/main/java/club/dnd5/portal/model/JsonStorageCompositeKey.java
  src/main/java/club/dnd5/portal/model/exporter/JsonStorage.java
  src/main/java/club/dnd5/portal/repository/JsonStorageRepository.java
  src/main/java/club/dnd5/portal/service/InvitationServiceImpl.java
  src/main/java/club/dnd5/portal/service/JsonStorageService.java
  src/main/java/club/dnd5/portal/service/JsonStorageServiceImpl.java
  src/main/java/club/dnd5/portal/service/LssService.java
  src/main/java/club/dnd5/portal/service/LssServiceImp.java
Labels: feature

#121 Bugfix/import foundry
  src/main/java/club/dnd5/portal/controller/api/LssApiController.java
  src/main/java/club/dnd5/portal/model/FoundryVersion.java
  src/main/java/club/dnd5/portal/service/JsonStorageServiceImpl.java
Labels: bug
