Repository TTG-Club/ttg-club-backend, pull requests merged in 2024-06, with the labels that each got.

#135 Добавлении источника к списку
  src/main/java/club/dnd5/portal/dto/api/classes/BackgroundApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/BackgroundDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/FeatApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/FeatDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/OptionApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/OptionDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ItemApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ItemDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/item/WeaponApi.java
  src/main/java/club/dnd5/portal/dto/api/item/WeaponDetailApi.java
Labels: bug

#136 fix(WebSecurityConfig): permanent redirect
  src/main/java/club/dnd5/portal/config/WebSecurityConfig.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ItemApi.java
  src/main/java/club/dnd5/portal/dto/api/item/WeaponApi.java
  src/main/java/club/dnd5/portal/dto/api/spells/SpellFvtt.java
  src/main/java/club/dnd5/portal/interceptor/RedirectToLowerCaseInterceptor.java
  src/main/java/club/dnd5/portal/model/background/Background.java
  src/main/java/club/dnd5/portal/model/classes/HeroClass.java
  src/main/java/club/dnd5/portal/model/classes/Option.java
  src/main/java/club/dnd5/portal/model/classes/archetype/Archetype.java
  src/main/java/club/dnd5/portal/model/creature/Creature.java
  src/main/java/club/dnd5/portal/model/god/God.java
  src/main/java/club/dnd5/portal/model/items/Armor.java
  src/main/java/club/dnd5/portal/model/items/Equipment.java
  src/main/java/club/dnd5/portal/model/items/MagicItem.java
  src/main/java/club/dnd5/portal/model/items/Weapon.java
  src/main/java/club/dnd5/portal/model/races/Race.java
  src/main/java/club/dnd5/portal/model/screen/Screen.java
  src/main/java/club/dnd5/portal/model/splells/Spell.java
  src/main/java/club/dnd5/portal/model/trait/Trait.java
  src/main/java/club/dnd5/portal/util/StringUtil.java
Labels: feature

#137 new release
  src/main/java/club/dnd5/portal/config/WebSecurityConfig.java
  src/main/java/club/dnd5/portal/controller/api/item/ArmorApiController.java
  src/main/java/club/dnd5/portal/controller/api/item/ItemApiController.java
  src/main/java/club/dnd5/portal/controller/api/item/WeaponApiController.java
  src/main/java/club/dnd5/portal/dto/api/SourceApi.java
  src/main/java/club/dnd5/portal/dto/api/UrlApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/BackgroundApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/BackgroundDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/FeatApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/FeatDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/OptionApi.java
  src/main/java/club/dnd5/portal/dto/api/classes/OptionDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorFilter.java
  src/main/java/club/dnd5/portal/dto/api/item/ArmorRequestApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ItemApi.java
  src/main/java/club/dnd5/portal/dto/api/item/ItemDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/item/WeaponApi.java
  src/main/java/club/dnd5/portal/dto/api/item/WeaponDetailApi.java
  src/main/java/club/dnd5/portal/dto/api/spells/SpellFvtt.java
  src/main/java/club/dnd5/portal/interceptor/RedirectToLowerCaseInterceptor.java
  src/main/java/club/dnd5/portal/model/background/Background.java
  src/main/java/club/dnd5/portal/model/book/Book.java
  src/main/java/club/dnd5/portal/model/classes/HeroClass.java
  src/main/java/club/dnd5/portal/model/classes/Option.java
  src/main/java/club/dnd5/portal/model/classes/archetype/Archetype.java
  src/main/java/club/dnd5/portal/model/creature/Creature.java
  src/main/java/club/dnd5/portal/model/god/God.java
  src/main/java/club/dnd5/portal/model/items/Armor.java
  src/main/java/club/dnd5/portal/model/items/Equipment.java
  src/main/java/club/dnd5/portal/model/items/MagicItem.java
  src/main/java/club/dnd5/portal/model/items/Weapon.java
  src/main/java/club/dnd5/portal/model/races/Race.java
  src/main/java/club/dnd5/portal/model/rule/Rule.java
  src/main/java/club/dnd5/portal/model/screen/Screen.java
  src/main/java/club/dnd5/portal/model/splells/Spell.java
  src/main/java/club/dnd5/portal/model/trait/Trait.java
  src/main/java/club/dnd5/portal/util/StringUtil.java
  src/main/resources/templates/fragments/archetype.html
Labels: release
