Repository TTG-Club/ttg-club-backend, pull requests merged in 2024-05, with the labels that each got.

#128 hotfix/markdown
  src/main/java/club/dnd5/portal/util/MarkdownUtil.java
Labels: bug

#130 new release
  src/main/java/club/dnd5/portal/util/MarkdownUtil.java
  src/test/java/club/dnd5/portal/MarkdownTest.java
Labels: release

#131 Хотфикс фильтров в бестиарии (урон)
  src/main/java/club/dnd5/portal/controller/api/bestiary/BestiaryApiController.java
  src/main/java/club/dnd5/portal/model/DamageType.java
Labels: bug

#133 Хотфикс групп классов
  src/main/java/club/dnd5/portal/dto/api/classes/ClassApi.java
  src/main/java/club/dnd5/portal/dto/api/races/RaceApi.java
Labels: enhancement

#132 hotfix/filters
  src/main/java/club/dnd5/portal/controller/api/bestiary/BestiaryApiController.java
  src/main/java/club/dnd5/portal/dto/api/classes/ClassApi.java
  src/main/java/club/dnd5/portal/dto/api/races/RaceApi.java
  src/main/java/club/dnd5/portal/model/DamageType.java
Labels: bug

#134 Переделка групп источников
  src/main/java/club/dnd5/portal/dto/api/SourceApi.java
Labels: enhancement
